<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NetworkAttackDetectionPlatform.MachineLearning/NetworkAttackDetectionPlatform.MachineLearning.csproj" />
  </ItemGroup>

</Project>
