<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetworkAttackDetectionPlatform.Domain\NetworkAttackDetectionPlatform.Domain.csproj" />
    <ProjectReference Include="..\NetworkAttackDetectionPlatform.Application\NetworkAttackDetectionPlatform.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
